# Generated by Django 5.2.17 on 2026-08-16 14:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingExportSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0, help_text="Série « E- » de CE centre : verrouillée le temps de l'émission, jamais un verrou sur la ligne du centre lui-même.", verbose_name='dernier numéro attribué')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_export_series', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'compteur de la série des exports comptables',
                'verbose_name_plural': "compteurs des séries d'exports comptables",
            },
        ),
        migrations.CreateModel(
            name='AccountingExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('period_start', models.DateField(verbose_name='début de période (jour local inclus)')),
                ('period_end', models.DateField(verbose_name='fin de période (jour local inclus)')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='numéro séquentiel')),
                ('total_collected_kmf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='total encaissé (KMF)')),
                ('total_reversed_kmf', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Somme des contre-passations DATÉES DANS LA PÉRIODE — jamais soustraites d'un jour antérieur (décision 7).", max_digits=14, verbose_name='total contre-passé (KMF)')),
                ('net_kmf', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Somme algébrique de ce qui est écrit : encaissé − contre-passé.', max_digits=14, verbose_name='net de la période (KMF)')),
                ('line_count', models.PositiveIntegerField(default=0, verbose_name='nombre de mouvements')),
                ('lines', models.JSONField(default=list, help_text="SNAPSHOT complet, relu tel quel au téléchargement — jamais recalculé. Des références et des montants, aucun nom, aucun libellé d'acte.", verbose_name='mouvements figés')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_exports', to='centers.healthcenter', verbose_name='centre')),
                ('generated_by', models.ForeignKey(help_text='Un humain déclenche et signe la photo — jamais un automate.', on_delete=django.db.models.deletion.PROTECT, related_name='accounting_exports_generated', to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
            ],
            options={
                'verbose_name': 'export comptable',
                'verbose_name_plural': 'exports comptables',
                'ordering': ['-sequence_number', '-id'],
                'indexes': [models.Index(fields=['center', '-created_at'], name='accounting__center__6b0a3d_idx'), models.Index(fields=['center', 'period_start', 'period_end'], name='accounting__center__f7adfd_idx')],
                'constraints': [models.UniqueConstraint(fields=('center', 'sequence_number'), name='unique_accounting_export_sequence_per_center'), models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='accounting_export_period_is_ordered'), models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='accounting_export_sequence_is_positive')],
            },
        ),
    ]
