# Generated by Django 5.2.17 on 2026-08-12 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de la consultation')),
                ('reason', models.CharField(max_length=255, verbose_name='motif')),
                ('diagnosis', models.TextField(blank=True, verbose_name='diagnostic')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=16, verbose_name='statut')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='centers.healthcenter', verbose_name='centre')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patientprofile', verbose_name='patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='centers.staffmembership', verbose_name='praticien')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ActPerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('label_snapshot', models.CharField(blank=True, help_text="Copié depuis le tarif au moment de l'acte ; ne suit pas les changements de grille.", max_length=255, verbose_name='libellé (figé)')),
                ('generic_category', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('analyses_examens', 'Analyses et examens'), ('medicaments', 'Médicaments'), ('hospitalisation', 'Hospitalisation'), ('acte_technique', 'Acte technique'), ('soins_infirmiers', 'Soins infirmiers'), ('maternite', 'Maternité'), ('autre', 'Autre')], help_text='SNAPSHOT de la nature générique du tarif (ADR 0005). Seule information de soin exposée au tuteur sous la portée « paiements » ; le libellé détaillé relève de « detail_clinique ».', max_length=24, verbose_name='nature générique (figée)')),
                ('price_kmf_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text="Copié depuis le tarif au moment de l'acte.", max_digits=12, null=True, verbose_name='prix KMF (figé)')),
                ('tariff_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts_performed', to='centers.tariffitem', verbose_name='tarif appliqué')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='medical.encounter', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'acte réalisé',
                'verbose_name_plural': 'actes réalisés',
            },
        ),
        migrations.CreateModel(
            name='HealthRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('entry_type', models.CharField(choices=[('antecedent', 'Antécédent'), ('allergie', 'Allergie'), ('traitement_en_cours', 'Traitement en cours'), ('vaccination', 'Vaccination')], max_length=24, verbose_name='type')),
                ('content', models.TextField(verbose_name='contenu')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_record_entries', to='patients.patientprofile', verbose_name='patient')),
                ('source_encounter', models.ForeignKey(blank=True, help_text="Renseigné quand l'entrée provient d'une consultation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_record_entries', to='medical.encounter', verbose_name='consultation source')),
            ],
            options={
                'verbose_name': 'entrée du carnet de santé',
                'verbose_name_plural': 'entrées du carnet de santé',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('status', models.CharField(choices=[('emise', 'Émise'), ('delivree', 'Délivrée')], default='emise', max_length=16, verbose_name='statut')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medical.encounter', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'ordonnance',
                'verbose_name_plural': 'ordonnances',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('medication', models.CharField(max_length=255, verbose_name='médicament')),
                ('dosage', models.TextField(blank=True, verbose_name='posologie')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.prescription', verbose_name='ordonnance')),
            ],
            options={
                'verbose_name': "ligne d'ordonnance",
                'verbose_name_plural': "lignes d'ordonnance",
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('scope', models.CharField(choices=[('paiements', 'Demandes de paiement, montants, nature générique, reçus (minimum)'), ('detail_clinique', 'Détail clinique : ordonnances détaillées, éléments du carnet')], max_length=24, verbose_name='portée')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='accordé le')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoqué le')),
                ('guardian_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.guardianlink', verbose_name='lien de tutelle')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.patientprofile', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'consentement',
                'verbose_name_plural': 'consentements',
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('guardian_link', 'scope'), name='unique_active_consent_per_link_and_scope')],
            },
        ),
    ]
