# Generated by Django 5.2.17 on 2026-08-13 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text="Agent du centre qui a recueilli le consentement au guichet (patient non revendiqué, porte C). Vide quand le patient l'accorde lui-même depuis son espace.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents_collected', to=settings.AUTH_USER_MODEL, verbose_name='recueilli par'),
        ),
        migrations.AddField(
            model_name='consent',
            name='collected_via',
            field=models.CharField(blank=True, choices=[('papier', 'Formulaire papier signé au guichet'), ('oral', 'Recueil oral au guichet')], help_text="Mode de recueil au guichet (papier signé / oral). Vide quand le patient l'accorde lui-même depuis son espace.", max_length=8, verbose_name='mode de recueil'),
        ),
    ]
