# Generated by Django 5.2.17 on 2026-08-14 15:12

import apps.common.private_storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_tariffitem_tariff_price_kmf_integral'),
        ('medical', '0002_consent_desk_collection_trace'),
        ('patients', '0004_extended_identity_and_insurance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecordentry',
            name='entry_type',
            field=models.CharField(choices=[('antecedent', 'Antécédent'), ('allergie', 'Allergie'), ('traitement_en_cours', 'Traitement en cours'), ('vaccination', 'Vaccination'), ('chirurgie', 'Chirurgie / hospitalisation antérieure'), ('antecedent_familial', 'Antécédent familial'), ('observation', "Observation (note d'évolution)")], max_length=24, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('doc_type', models.CharField(choices=[('resultat_biologie', 'Résultat de biologie'), ('imagerie', 'Imagerie'), ('compte_rendu', 'Compte rendu'), ('autre', 'Autre')], max_length=24, verbose_name='type de document')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('file', models.FileField(max_length=255, storage=apps.common.private_storage.PrivateMediaStorage(), upload_to='patient_documents/%Y/%m/', verbose_name='fichier')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_documents_archived', to=settings.AUTH_USER_MODEL, verbose_name='archivé par')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_documents', to='centers.healthcenter', verbose_name='centre producteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='patients.patientprofile', verbose_name='patient')),
                ('source_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='medical.encounter', verbose_name='consultation source')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
            ],
            options={
                'verbose_name': 'document patient',
                'verbose_name_plural': 'documents patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A−'), ('B+', 'B+'), ('B-', 'B−'), ('AB+', 'AB+'), ('AB-', 'AB−'), ('O+', 'O+'), ('O-', 'O−')], max_length=3, verbose_name='groupe sanguin')),
                ('notes', models.TextField(blank=True, verbose_name='notes cliniques')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_file', to='patients.patientprofile', verbose_name='patient')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_medical_files_updated', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'fiche médicale patient',
                'verbose_name_plural': 'fiches médicales patients',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='mesuré le')),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PA systolique (mmHg)')),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PA diastolique (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='fréquence cardiaque (bpm)')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO₂ (%)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='température (°C)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='fréquence respiratoire (/min)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='poids (kg)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='taille (cm)')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='medical.encounter', verbose_name='consultation')),
                ('measured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs_measured', to='centers.staffmembership', verbose_name='mesuré par')),
            ],
            options={
                'verbose_name': 'signes vitaux',
                'verbose_name_plural': 'signes vitaux',
                'ordering': ['-measured_at', '-id'],
            },
        ),
    ]
