# Generated by Django 5.2.17 on 2026-08-16 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_enriched_patient_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='délivrée le'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_delivered', to=settings.AUTH_USER_MODEL, verbose_name='délivrée par'),
        ),
    ]
