# Generated by Django 5.2.17 on 2026-08-15 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('category', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('imagerie', 'Imagerie'), ('bloc_operatoire', 'Bloc opératoire'), ('laboratoire', 'Laboratoire'), ('mobilier_medical', 'Mobilier médical'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=24, verbose_name='catégorie')),
                ('serial_number', models.CharField(blank=True, help_text="Champ libre : le réel comorien n'a pas de format, et deux appareils identiques sans numéro sont un cas normal.", max_length=64, verbose_name='numéro de série')),
                ('location', models.CharField(blank=True, help_text="Texte libre (ADR 0021 décision 2) — jamais une chambre : tous les centres n'ont pas d'hospitalisation.", max_length=120, verbose_name='emplacement')),
                ('commissioned_on', models.DateField(blank=True, null=True, verbose_name='mis en service le')),
                ('status', models.CharField(choices=[('en_service', 'En service'), ('en_panne', 'En panne'), ('reforme', 'Réformé')], default='en_service', max_length=16, verbose_name='état')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'équipement',
                'verbose_name_plural': 'équipements',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('description', models.TextField(verbose_name='description')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='equipment.equipment', verbose_name='équipement')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_reports', to=settings.AUTH_USER_MODEL, verbose_name='signalé par')),
            ],
            options={
                'verbose_name': "signalement d'équipement",
                'verbose_name_plural': "signalements d'équipement",
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['center', 'status'], name='equipment_e_center__e9974d_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['en_service', 'en_panne', 'reforme'])), name='equipment_status_is_closed'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['diagnostic', 'imagerie', 'bloc_operatoire', 'laboratoire', 'mobilier_medical', 'informatique', 'autre'])), name='equipment_category_is_closed'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='equipment_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='equipmentreport',
            index=models.Index(fields=['equipment', '-created_at'], name='equipment_e_equipme_e8d1f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentreport',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='equipment_report_description_not_empty'),
        ),
    ]
