# Generated by Django 5.2.17 on 2026-08-12 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('action', models.CharField(help_text='Verbe qualifié, ex. « payment_request.created », « consent.revoked ».', max_length=128, verbose_name='action')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='identifiant cible')),
                ('payload', models.JSONField(blank=True, default=dict, help_text="Contexte minimal de l'action — jamais de donnée clinique en clair inutile.", verbose_name='données')),
                ('actor', models.ForeignKey(blank=True, help_text='Vide pour les actions système (webhooks PSP, tâches planifiées…).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='contenttypes.contenttype', verbose_name='type de cible')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
