# Generated by Django 5.2.17 on 2026-08-14 22:00
#
# S5 (ADR 0018 décisions 1 à 3) — le registre SÉPARÉ de l'abonnement SaaS.
# Deux tables neuves, aucune donnée touchée ailleurs : schéma seul,
# entièrement réversible (aucun RunPython, aucun rétro-remplissage). La
# contrainte `subscription_plan_price_kmf_integral` naît avec la table —
# contrairement à `centers/0004` (tarifs), elle n'a aucun existant
# fractionnaire à refuser.

import apps.common.money
import django.db.models.deletion
import django.db.models.functions.math
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('code', models.CharField(help_text="Identifiant stable de l'offre, ex. « ESSENTIEL ».", max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=128, verbose_name='nom commercial')),
                ('price_kmf', models.DecimalField(decimal_places=2, help_text="Prix par période de facturation, en francs entiers. Les factures déjà émises portent leur propre montant figé : changer ce prix n'a jamais d'effet rétroactif.", max_digits=12, validators=[apps.common.money.validate_kmf_integral], verbose_name='prix (KMF)')),
                ('billing_period', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=16, verbose_name='période de facturation')),
                ('included_practitioners', models.PositiveIntegerField(blank=True, help_text='Vide = illimité. Quota INDICATIF : ne bloque jamais rien.', null=True, verbose_name='praticiens inclus')),
                ('included_staff', models.PositiveIntegerField(blank=True, help_text='Vide = illimité. Quota INDICATIF : ne bloque jamais rien.', null=True, verbose_name='membres du personnel inclus')),
                ('is_active', models.BooleanField(default=True, help_text='Une offre retirée reste référencée par les abonnements en cours — jamais de suppression.', verbose_name='proposé à la vente')),
            ],
            options={
                'verbose_name': "offre d'abonnement",
                'verbose_name_plural': "offres d'abonnement",
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_kmf__gte', 0)), name='subscription_plan_price_positive'), models.CheckConstraint(condition=models.Q(('price_kmf', django.db.models.functions.math.Round('price_kmf'))), name='subscription_plan_price_kmf_integral')],
            },
        ),
        migrations.CreateModel(
            name='CenterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('status', models.CharField(choices=[('essai', 'Essai'), ('actif', 'Actif'), ('impaye', 'Impayé'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='essai', help_text="Axe INDÉPENDANT du KYC. Seuls « suspendu » et « résilié » gèlent l'administratif (personnel, tarifs, statistiques) — jamais le soin, jamais la caisse.", max_length=16, verbose_name="statut de l'abonnement")),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='démarré le')),
                ('current_period_end', models.DateField(blank=True, help_text='Date à laquelle la période en cours est due. La facturation SaaS (émission, relances, règlements) est le lot 2.', null=True, verbose_name='échéance de la période en cours')),
                ('status_reason', models.TextField(blank=True, help_text="Obligatoire pour suspendre ou résilier. Visible de la plateforme et du directeur du centre — jamais d'un patient ni d'un tuteur.", verbose_name='motif de la dernière décision')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='statut décidé le')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='centers.healthcenter', verbose_name='centre')),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_decisions', to=settings.AUTH_USER_MODEL, verbose_name='statut décidé par')),
                ('plan', models.ForeignKey(help_text="L'offre est RÉFÉRENCÉE : ses prix passés ne sont jamais réécrits dans les factures déjà émises.", on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan', verbose_name='offre')),
            ],
            options={
                'verbose_name': "abonnement d'un centre",
                'verbose_name_plural': 'abonnements des centres',
                'ordering': ['center__name'],
            },
        ),
    ]
