# Generated by Django 5.2.17 on 2026-08-14 22:38
#
# S5 lot 2 (ADR 0018 décision 4) — la facturation SaaS Chioni → centre.
# Quatre tables neuves, aucune donnée touchée ailleurs : schéma seul,
# entièrement réversible (aucun RunPython, aucun rétro-remplissage) — et
# surtout AUCUNE table du ledger des soins n'est modifiée (décision 1 : les
# deux registres restent séparés).
#
# La ligne unique du compteur de la série « A- » n'est PAS semée ici : elle
# est créée à la volée par le service de numérotation. Une migration de
# données serait un piège — ``TransactionTestCase`` vide les tables entre
# deux tests, et la numérotation dépendrait alors d'une ligne disparue.
#
# L'unicité (subscription, period_start) est PARTIELLE (factures vivantes
# seulement) : annuler une facture doit rendre sa période re-facturable,
# sinon une faute de frappe rendrait un tenant définitivement non
# facturable pour ce mois-là.

import apps.common.money
import django.db.models.deletion
import django.db.models.functions.math
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('centers', '0005_kyc_file_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0, help_text="Série « A- » GLOBALE Chioni : verrouillée le temps de l'émission, jamais un verrou sur un centre.", verbose_name='dernier numéro attribué')),
            ],
            options={
                'verbose_name': "compteur de la série des factures d'abonnement",
                'verbose_name_plural': "compteur de la série des factures d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('sequence_number', models.PositiveIntegerField(help_text='Global à Chioni — jamais par tenant (ADR 0018 décision 4).', verbose_name='numéro de la série « A- »')),
                ('period_start', models.DateField(verbose_name='début de période')),
                ('period_end', models.DateField(verbose_name='fin de période (incluse)')),
                ('amount_kmf', models.DecimalField(decimal_places=2, help_text="Figé à l'émission : un changement de prix de l'offre n'y touche jamais.", max_digits=12, validators=[apps.common.money.validate_kmf_integral], verbose_name='montant (KMF)')),
                ('plan_code', models.CharField(help_text="SNAPSHOT — l'offre peut être renommée ou repricée ensuite.", max_length=32, verbose_name="code de l'offre (figé)")),
                ('plan_label', models.CharField(max_length=128, verbose_name="nom de l'offre (figé)")),
                ('due_date', models.DateField(help_text="Une échéance dépassée fait passer l'abonnement en « impayé » (alerte), jamais en « suspendu » (sanction, décision humaine).", verbose_name='échéance')),
                ('status', models.CharField(choices=[('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='emise', max_length=16, verbose_name='statut')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('cancel_reason', models.TextField(blank=True, help_text="Obligatoire à l'annulation. Écrit par Chioni POUR le directeur du centre : il le lit sur sa facture — jamais dans un payload d'audit (même règle que ``Invoice.cancel_reason``).", verbose_name="motif d'annulation")),
                ('reminders_sent', models.PositiveSmallIntegerField(default=0, verbose_name='relances envoyées')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière relance')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('center', models.ForeignKey(help_text="Dénormalisé depuis l'abonnement par le service — jamais une entrée client (patron ``CashPayment.center``).", on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', to='centers.healthcenter', verbose_name='centre')),
                ('issued_by', models.ForeignKey(blank=True, help_text="Exploitant Chioni ; vide pour l'émission automatique (tâche planifiée).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices_issued', to=settings.AUTH_USER_MODEL, verbose_name='émise par')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.centersubscription', verbose_name='abonnement')),
            ],
            options={
                'verbose_name': "facture d'abonnement",
                'verbose_name_plural': "factures d'abonnement",
                'ordering': ['-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('amount_kmf', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.common.money.validate_kmf_integral], verbose_name='montant (KMF)')),
                ('method', models.CharField(choices=[('virement', 'Virement'), ('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('autre', 'Autre')], max_length=16, verbose_name='moyen de règlement')),
                ('reference', models.CharField(blank=True, help_text='Ex. référence du virement ou de la transaction mobile money.', max_length=64, verbose_name='référence externe')),
                ('received_at', models.DateField(default=django.utils.timezone.localdate, help_text='Date réelle de réception des fonds — jamais dans le futur.', verbose_name='reçu le')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.subscriptioninvoice', verbose_name="facture d'abonnement")),
                ('recorded_by', models.ForeignKey(help_text='Exploitant de la plateforme Chioni.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='saisi par')),
            ],
            options={
                'verbose_name': "règlement d'abonnement",
                'verbose_name_plural': "règlements d'abonnement",
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('reason', models.TextField(help_text='Obligatoire — une contre-passation sans motif est irrecevable.', verbose_name='motif')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='billing.subscriptionpayment', verbose_name='règlement')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payment_reversals_made', to=settings.AUTH_USER_MODEL, verbose_name='contre-passé par')),
            ],
            options={
                'verbose_name': "contre-passation d'un règlement d'abonnement",
                'verbose_name_plural': "contre-passations de règlements d'abonnement",
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(fields=('sequence_number',), name='unique_subscription_invoice_sequence'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'annulee'), _negated=True), fields=('subscription', 'period_start'), name='unique_live_subscription_invoice_period'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf__gt', 0)), name='subscription_invoice_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf', django.db.models.functions.math.Round('amount_kmf'))), name='subscription_invoice_amount_kmf_integral'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='subscription_invoice_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('period_start'))), name='subscription_invoice_due_after_period_start'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf__gt', 0)), name='subscription_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf', django.db.models.functions.math.Round('amount_kmf'))), name='subscription_payment_amount_kmf_integral'),
        ),
    ]
