# Generated by Django 5.2.17 on 2026-08-12 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('country_of_residence', models.CharField(default='FR', help_text='Code ISO 3166-1 alpha-2 (FR, RE, YT, AE…).', max_length=2, verbose_name='pays de résidence')),
                ('preferred_currency', models.CharField(choices=[('EUR', 'Euro'), ('KMF', 'Franc comorien')], default='EUR', max_length=3, verbose_name='devise préférée')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur')),
            ],
            options={
                'verbose_name': 'profil tuteur',
                'verbose_name_plural': 'profils tuteurs',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('claim_status', models.CharField(choices=[('non_revendique', 'Non revendiqué'), ('invite', 'Invité (SMS envoyé)'), ('actif', 'Actif (compte revendiqué)')], default='non_revendique', max_length=16, verbose_name='statut de revendication')),
                ('last_name', models.CharField(max_length=128, verbose_name='nom')),
                ('first_name', models.CharField(max_length=128, verbose_name='prénom')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('sex', models.CharField(blank=True, choices=[('f', 'Féminin'), ('m', 'Masculin')], max_length=1, verbose_name='sexe')),
                ('phone', models.CharField(blank=True, help_text="Déclaratif, NON unique : seul le téléphone du compte User est vérifié par OTP. Sert au rapprochement de doublons et à l'invitation SMS.", max_length=32, verbose_name='téléphone')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='ville / village')),
                ('created_by_center', models.ForeignKey(blank=True, help_text="Renseigné quand le profil a été créé au guichet d'un centre (porte C).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_profiles_created', to='centers.healthcenter', verbose_name='créé par (centre)')),
                ('created_by_user', models.ForeignKey(blank=True, help_text='Tuteur (porte A), le patient lui-même (porte B) ou agent du centre (porte C).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par (utilisateur)')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Si renseigné, ce profil est un doublon absorbé par le profil canonique pointé.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_duplicates', to='patients.patientprofile', verbose_name='fusionné dans')),
                ('user', models.OneToOneField(blank=True, help_text="Vide tant que le profil n'est pas revendiqué par le patient (portes A et C).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur')),
            ],
            options={
                'verbose_name': 'profil patient',
                'verbose_name_plural': 'profils patients',
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('relationship', models.CharField(choices=[('parent', 'Parent (père / mère)'), ('enfant', 'Enfant (fils / fille)'), ('conjoint', 'Conjoint / Conjointe'), ('frere_soeur', 'Frère / Sœur'), ('famille_elargie', 'Famille élargie (oncle, tante, cousin…)'), ('ami', 'Ami / Amie'), ('autre', 'Autre')], help_text='Lien du tuteur envers le protégé.', max_length=16, verbose_name='lien de parenté')),
                ('status', models.CharField(choices=[('invitation_envoyee', 'Invitation envoyée'), ('actif', 'Actif'), ('revoque', 'Révoqué')], default='invitation_envoyee', max_length=24, verbose_name='statut')),
                ('initiated_by', models.CharField(choices=[('tuteur', 'Le tuteur (porte A)'), ('patient', 'Le patient (porte B)'), ('centre', 'Le centre de santé (porte C)')], max_length=8, verbose_name='initié par')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepté le')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoqué le')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='patients.guardianprofile', verbose_name='tuteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='patients.patientprofile', verbose_name='protégé')),
            ],
            options={
                'verbose_name': 'lien de tutelle',
                'verbose_name_plural': 'liens de tutelle',
            },
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_status', 'actif'), ('user__isnull', False)), models.Q(('claim_status', 'actif'), _negated=True), _connector='OR'), name='active_patient_profile_requires_user'),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), models.Q(('merged_into', models.F('id')), _negated=True), _connector='OR'), name='patient_profile_no_self_merge'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(fields=('guardian', 'patient'), name='unique_guardian_patient_link'),
        ),
    ]
