# Generated by Django 5.2.17 on 2026-08-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_revoked_link_final_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianlink',
            name='status',
            field=models.CharField(choices=[('invitation_envoyee', 'Invitation envoyée'), ('attente_confirmation_titulaire', 'En attente de confirmation du titulaire'), ('actif', 'Actif'), ('revoque', 'Révoqué')], default='invitation_envoyee', max_length=32, verbose_name='statut'),
        ),
    ]
