# Generated by Django 5.2.17 on 2026-08-14 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_guardianlink_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='personne à prévenir (nom)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Normalisé E.164 comme « téléphone ».', max_length=32, verbose_name='personne à prévenir (téléphone)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=64, verbose_name='personne à prévenir (lien)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(blank=True, help_text='Texte libre — aucun format imposé (réalité comorienne : CNI, passeport ou identifiant médical local).', max_length=64, verbose_name="n° d'identité / identifiant médical"),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_alt',
            field=models.CharField(blank=True, help_text='Déclaratif, normalisé E.164 comme « téléphone ».', max_length=32, verbose_name='second téléphone'),
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('insurer_name', models.CharField(max_length=128, verbose_name='assureur / mutuelle')),
                ('member_number', models.CharField(max_length=64, verbose_name="numéro d'adhérent")),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_insurances_created', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurances', to='patients.patientprofile', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'assurance patient',
                'verbose_name_plural': 'assurances patients',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
