# Generated by Django 5.2.17 on 2026-08-16 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_extended_identity_and_insurance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofile',
            name='payment_reminders',
            field=models.BooleanField(default=True, help_text="Relances SMS des factures impayées de ses protégés. La notification INITIALE d'une demande de paiement et le reçu ne sont jamais couverts par ce refus.", verbose_name='relances de paiement'),
        ),
        migrations.CreateModel(
            name='PatientContactPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('appointment_reminders', models.BooleanField(default=True, help_text='Rappel J-1 (ADR 0013) — refusable depuis S10.', verbose_name='rappels de rendez-vous')),
                ('missed_appointment_followup', models.BooleanField(default=True, help_text='Message unique et neutre du lendemain (ADR 0023 décision 5).', verbose_name='reprise de contact après un rendez-vous manqué')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contact_preference', to='patients.patientprofile', verbose_name='patient')),
                ('updated_by', models.ForeignKey(help_text="La personne elle-même, ou l'agent du guichet (profil non revendiqué).", on_delete=django.db.models.deletion.PROTECT, related_name='patient_contact_preferences_updated', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'préférences de contact du patient',
                'verbose_name_plural': 'préférences de contact des patients',
            },
        ),
    ]
