# Generated by Django 5.2.17 on 2026-08-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        ('patients', '0005_guardianprofile_payment_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianlink',
            name='initiated_by_center',
            field=models.ForeignKey(blank=True, help_text="Centre qui a émis l'invitation quand le lien est né au guichet (porte C). Vide pour les portes A/B et pour les liens historiques antérieurs à SV (provenance non dérivable — fail-closed sur le consentement clinique guichet).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_guardian_links', to='centers.healthcenter', verbose_name='centre initiateur'),
        ),
    ]
