# Generated by Django 5.2.17 on 2026-08-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text="Posé à la PREMIÈRE vérification OTP réussie. NULL = compte ombre (invitation/guichet) ou compte n'ayant jamais vérifié son numéro ; la pose vaut activation du compte (ADR 0010).", null=True, verbose_name='téléphone vérifié le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Identifiant pivot de la plateforme (vérifié par OTP SMS — ADR 0010). Format international E.164, ex. +2693212345.', max_length=32, null=True, unique=True, verbose_name='numéro de téléphone'),
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Numéro destinataire, normalisé E.164 AVANT toute écriture.', max_length=32, verbose_name='téléphone (E.164)')),
                ('code_hash', models.CharField(help_text="HMAC-SHA256 (clé SECRET_KEY) du code — le code en clair n'est jamais stocké.", max_length=64, verbose_name='empreinte du code')),
                ('purpose', models.CharField(choices=[('login', 'Connexion')], default='login', max_length=16, verbose_name='finalité')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives de vérification')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consommé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'indexes': [models.Index(fields=['phone', 'purpose'], name='otp_phone_purpose_idx')],
            },
        ),
    ]
