# Generated by Django 5.2.17 on 2026-08-13 16:30

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_verified_at_alter_user_phone_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.user_avatar_upload_to, verbose_name='photo de profil'),
        ),
    ]
