# Generated by Django 5.2.17 on 2026-08-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('role', models.CharField(choices=[('support', 'Support'), ('admin', 'Administrateur plateforme')], help_text='« support » lit (centres, KYC, réconciliation) ; « admin » seul écrit (créer un centre, changer un KYC).', max_length=16, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='platform_staff', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "membre de l'équipe Chioni",
                'verbose_name_plural': 'équipe Chioni (plateforme)',
                'ordering': ['user__username'],
            },
        ),
    ]
