# Generated by Django 5.2.17 on 2026-08-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_anonymized_at_erasurerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasurerequest',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée'), ('refusee', 'Refusée'), ('annulee', 'Annulée par la personne')], default='en_attente', max_length=16, verbose_name='statut'),
        ),
    ]
