# Generated by Django 5.2.17 on 2026-08-16 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        ('patients', '0005_guardianprofile_payment_reminders_and_more'),
        ('scheduling', '0001_initial'),
        ('trustbridge', '0008_cashpayment_idempotency_key_invoice_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('kind', models.CharField(choices=[('relance_impaye', "Relance d'impayé"), ('reprise_contact', 'Reprise de contact (rendez-vous manqué)')], max_length=24, verbose_name='motif')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('appel', 'Appel téléphonique'), ('guichet', 'Au guichet')], max_length=8, verbose_name='canal')),
                ('recipient', models.CharField(choices=[('patient', 'Le patient'), ('tuteur', 'Un proche de confiance')], max_length=8, verbose_name='destinataire')),
                ('outcome', models.CharField(blank=True, choices=[('joint', 'Joint'), ('sans_reponse', 'Sans réponse'), ('promesse_de_reglement', 'Promesse de règlement'), ('a_rappeler', 'À rappeler')], help_text="Vide pour un envoi automatique : personne n'était au bout du fil.", max_length=24, verbose_name='issue')),
                ('appointment', models.ForeignKey(blank=True, help_text='Obligatoire pour une reprise de contact, interdit sinon.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='scheduling.appointment', verbose_name='rendez-vous')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='centers.healthcenter', verbose_name='centre')),
                ('created_by', models.ForeignKey(blank=True, help_text="NULL = l'automate (tâche planifiée).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs_made', to=settings.AUTH_USER_MODEL, verbose_name='contact effectué par')),
                ('invoice', models.ForeignKey(blank=True, help_text="Obligatoire pour une relance d'impayé, interdite sinon.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='trustbridge.invoice', verbose_name='facture')),
                ('patient', models.ForeignKey(help_text='Le patient dont il est question — pas nécessairement le destinataire (voir « recipient »).', on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='patients.patientprofile', verbose_name='patient concerné')),
            ],
            options={
                'verbose_name': 'trace de contact',
                'verbose_name_plural': 'traces de contact',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['invoice', 'kind'], name='crm_contact_invoice_c55e36_idx'), models.Index(fields=['appointment', 'kind'], name='crm_contact_appoint_064a2e_idx'), models.Index(fields=['center', '-created_at'], name='crm_contact_center__a8c6ce_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['relance_impaye', 'reprise_contact'])), name='contact_log_kind_is_closed'), models.CheckConstraint(condition=models.Q(('channel__in', ['sms', 'appel', 'guichet'])), name='contact_log_channel_is_closed'), models.CheckConstraint(condition=models.Q(('recipient__in', ['patient', 'tuteur'])), name='contact_log_recipient_is_closed'), models.CheckConstraint(condition=models.Q(('outcome', ''), ('outcome__in', ['joint', 'sans_reponse', 'promesse_de_reglement', 'a_rappeler']), _connector='OR'), name='contact_log_outcome_is_closed'), models.CheckConstraint(condition=models.Q(models.Q(('appointment__isnull', True), ('invoice__isnull', False), ('kind', 'relance_impaye')), models.Q(('appointment__isnull', False), ('invoice__isnull', True), ('kind', 'reprise_contact')), _connector='OR'), name='contact_log_reference_matches_kind')],
            },
        ),
    ]
