# Generated by Django 5.2.17 on 2026-08-16 19:40
"""SV — nouvelle issue fermée ``rdv_fixe`` (« Rendez-vous fixé »).

L'issue heureuse d'une reprise de contact : sans elle, le guichet qui
fixait un rendez-vous au téléphone devait choisir entre « joint » (vrai
mais pauvre) et ne rien journaliser. La contrainte de liste fermée
``contact_log_outcome_is_closed`` est régénérée avec la nouvelle valeur —
le texte libre reste impossible par construction (ADR 0023).
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        ('crm', '0002_sv_db_triggers'),
        ('patients', '0006_guardianlink_initiated_by_center'),
        ('scheduling', '0001_initial'),
        ('trustbridge', '0008_cashpayment_idempotency_key_invoice_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactlog',
            name='contact_log_outcome_is_closed',
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('joint', 'Joint'), ('sans_reponse', 'Sans réponse'), ('promesse_de_reglement', 'Promesse de règlement'), ('a_rappeler', 'À rappeler'), ('rdv_fixe', 'Rendez-vous fixé')], help_text="Vide pour un envoi automatique : personne n'était au bout du fil.", max_length=24, verbose_name='issue'),
        ),
        migrations.AddConstraint(
            model_name='contactlog',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', ''), ('outcome__in', ['joint', 'sans_reponse', 'promesse_de_reglement', 'a_rappeler', 'rdv_fixe']), _connector='OR'), name='contact_log_outcome_is_closed'),
        ),
    ]
