# Generated by Django 5.2.17 on 2026-08-12 23:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('medical', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('total_kmf', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Somme des lignes ; recalculée à chaque ajout de ligne, figée à l'émission.", max_digits=12, verbose_name='total (KMF)')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=16, verbose_name='statut')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='centers.healthcenter', verbose_name='centre')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='medical.encounter', verbose_name='consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patientprofile', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('label', models.CharField(blank=True, help_text="Libellé comptable détaillé — portée « detail_clinique » côté tuteur (ADR 0005) : ne jamais l'exposer via les vues de paiement.", max_length=255, verbose_name='libellé (figé)')),
                ('generic_category', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('analyses_examens', 'Analyses et examens'), ('medicaments', 'Médicaments'), ('hospitalisation', 'Hospitalisation'), ('acte_technique', 'Acte technique'), ('soins_infirmiers', 'Soins infirmiers'), ('maternite', 'Maternité'), ('autre', 'Autre')], help_text="SNAPSHOT depuis l'acte (ADR 0005) — seule information de soin visible du tuteur sous la portée « paiements ».", max_length=24, verbose_name='nature générique (figée)')),
                ('amount_kmf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant (KMF)')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='medical.actperformed', verbose_name='acte facturé')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trustbridge.invoice', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('center', models.ForeignKey(blank=True, help_text='Renseigné automatiquement par record() depuis la facture de la demande de paiement — reporting et rapprochement par centre.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'transaction du ledger',
                'verbose_name_plural': 'transactions du ledger',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('account', models.CharField(choices=[('fonds_tuteur', 'Fonds du tuteur'), ('du_au_centre', 'Dû au centre de santé'), ('frais_psp', 'Frais PSP'), ('frais_chioni', 'Frais Chioni'), ('conversion_change', 'Conversion de change EUR↔KMF')], max_length=24, verbose_name='compte')),
                ('direction', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=6, verbose_name='sens')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('KMF', 'Franc comorien')], max_length=3, verbose_name='devise')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text="Taux EUR→KMF figé, renseigné sur les écritures issues d'une conversion.", max_digits=12, null=True, verbose_name='taux appliqué')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='trustbridge.ledgertransaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'écriture du ledger',
                'verbose_name_plural': 'écritures du ledger',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('soin_confirme', 'Soin confirmé'), ('cloturee', 'Clôturée'), ('litige', 'Litige')], default='brouillon', max_length=16, verbose_name='statut')),
                ('created_by', models.ForeignKey(help_text="Agent du centre ou patient à l'origine de la demande.", on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='trustbridge.invoice', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'demande de paiement',
                'verbose_name_plural': 'demandes de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('psp', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=16, verbose_name='prestataire de paiement')),
                ('psp_reference', models.CharField(blank=True, help_text='Ex. identifiant PaymentIntent Stripe.', max_length=255, verbose_name='référence PSP')),
                ('idempotency_key', models.CharField(help_text='Unique : protège contre webhooks rejoués et doubles soumissions.', max_length=64, unique=True, verbose_name="clé d'idempotence")),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant payé (EUR)')),
                ('exchange_rate', models.DecimalField(decimal_places=6, help_text='Affiché au tuteur AVANT paiement, figé à la transaction.', max_digits=12, verbose_name='taux EUR→KMF figé')),
                ('amount_kmf', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant converti (KMF)')),
                ('status', models.CharField(choices=[('cree', 'Créé'), ('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='cree', max_length=16, verbose_name='statut PSP')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='patients.guardianprofile', verbose_name='tuteur payeur')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='trustbridge.paymentrequest', verbose_name='demande de paiement')),
            ],
            options={
                'verbose_name': 'intention de paiement',
                'verbose_name_plural': 'intentions de paiement',
            },
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='payment_request',
            field=models.ForeignKey(blank=True, help_text='Fléchage métier : chaque franc reste relié à une demande quand il y en a une.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='trustbridge.paymentrequest', verbose_name='demande de paiement'),
        ),
        migrations.CreateModel(
            name='PaymentRequestShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='partagée le')),
                ('guardian_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request_shares', to='patients.guardianlink', verbose_name='lien de tutelle')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='trustbridge.paymentrequest', verbose_name='demande de paiement')),
                ('shared_by', models.ForeignKey(blank=True, help_text='Agent du centre ou patient qui a ciblé ce tuteur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_request_shares_made', to=settings.AUTH_USER_MODEL, verbose_name='partagée par')),
            ],
            options={
                'verbose_name': 'partage de demande de paiement',
                'verbose_name_plural': 'partages de demandes de paiement',
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Liens de tutelle ciblés — seuls ces tuteurs voient la demande.', related_name='payment_requests', through='trustbridge.PaymentRequestShare', to='patients.guardianlink', verbose_name='partagée avec'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='numéro séquentiel')),
                ('amount_eur_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant payé (EUR)')),
                ('amount_kmf_received', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant reçu par le centre (KMF)')),
                ('fees_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='frais explicites (EUR)')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='taux EUR→KMF appliqué')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='émis le')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='centers.healthcenter', verbose_name='centre')),
                ('ledger_transaction', models.ForeignKey(help_text='M3 — la transaction du ledger qui solde la demande : les montants du reçu sont réconciliés avec le ledger, jamais seulement affirmés.', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='trustbridge.ledgertransaction', verbose_name='transaction de clôture')),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='trustbridge.paymentrequest', verbose_name='demande de paiement')),
            ],
            options={
                'verbose_name': 'reçu',
                'verbose_name_plural': 'reçus',
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_kmf__gte', 0)), name='invoice_total_kmf_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur__gt', 0)), name='payment_intent_amount_eur_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf__gt', 0)), name='payment_intent_amount_kmf_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='payment_intent_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequestshare',
            constraint=models.UniqueConstraint(fields=('payment_request', 'guardian_link'), name='unique_share_per_request_and_link'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('center', 'sequence_number'), name='unique_receipt_sequence_per_center'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_paid__gt', 0)), name='receipt_amount_eur_paid_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf_received__gt', 0)), name='receipt_amount_kmf_received_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('fees_eur__gte', 0)), name='receipt_fees_eur_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='receipt_exchange_rate_positive'),
        ),
    ]
