# Generated by Django 5.2.17 on 2026-08-13 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustbridge', '0003_validation_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='ledger_transaction',
            field=models.ForeignKey(blank=True, help_text="F2 — renseignée par le service d'encaissement au moment du succès : un intent SUCCEEDED est réconciliable avec SA transaction du ledger, jamais seulement affirmé. La clôture (reçu) s'appuie dessus.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='trustbridge.ledgertransaction', verbose_name="transaction d'encaissement"),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='patient_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage du « j'ai bien reçu ce soin » du patient — indicateur de mission (étude §10) : stocké, pas seulement audité.", null=True, verbose_name='accusé du patient le'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='psp',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('fake', 'Fake (développement)')], default='stripe', max_length=16, verbose_name='prestataire de paiement'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('reason', models.TextField(help_text='Obligatoire — un litige sans motif est irrecevable.', verbose_name='motif')),
                ('previous_status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('soin_confirme', 'Soin confirmé'), ('cloturee', 'Clôturée'), ('litige', 'Litige')], help_text="Statut de la demande au moment de l'ouverture — restauré à la résolution.", max_length=16, verbose_name='statut avant litige')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu')], default='ouvert', max_length=16, verbose_name='statut')),
                ('resolution_note', models.TextField(blank=True, verbose_name='motif de résolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolu le')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to=settings.AUTH_USER_MODEL, verbose_name='ouvert par')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='trustbridge.paymentrequest', verbose_name='demande de paiement')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL, verbose_name='résolu par')),
            ],
            options={
                'verbose_name': 'litige',
                'verbose_name_plural': 'litiges',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ouvert')), fields=('payment_request',), name='unique_open_dispute_per_request')],
            },
        ),
    ]
