# Generated by Django 5.2.17 on 2026-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustbridge', '0004_dispute_patient_ack_intent_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de l'encaissement — posé UNIQUEMENT par register_payment_success() dans le même bloc atomique que l'écriture du ledger, jamais modifié ensuite (un cycle litige/résolution ne l'efface pas). Confort de lecture pour les trois audiences ; le ledger reste la seule vérité financière.", null=True, verbose_name='payée le'),
        ),
    ]
