# Generated by Django 5.2.17 on 2026-08-13 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_healthcenter_logo'),
        ('trustbridge', '0005_paymentrequest_paid_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('fonds_tuteur', 'Fonds du tuteur'), ('du_au_centre', 'Dû au centre de santé'), ('frais_psp', 'Frais PSP'), ('frais_chioni', 'Frais Chioni'), ('conversion_change', 'Conversion de change EUR↔KMF'), ('caisse_especes', 'Caisse espèces'), ('mobile_money', 'Mobile money'), ('creances_patient', 'Créances patient')], max_length=24, verbose_name='compte'),
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('method', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('pont_confiance', 'Pont de Confiance')], max_length=16, verbose_name='moyen de paiement')),
                ('operator', models.CharField(blank=True, choices=[('huri', 'Huri Money (Comores Télécom)'), ('mvola', 'MVola (Telma)'), ('autre', 'Autre opérateur')], help_text='Obligatoire pour mobile money, interdit sinon (contrainte DB).', max_length=16, verbose_name='opérateur mobile money')),
                ('reference', models.CharField(blank=True, help_text='Ex. identifiant de transaction mobile money.', max_length=64, verbose_name='référence externe')),
                ('amount_kmf', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant (KMF)')),
                ('center', models.ForeignKey(help_text='Toujours dérivé de la facture par le service — jamais une entrée client.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='centers.healthcenter', verbose_name='centre')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='trustbridge.invoice', verbose_name='facture')),
                ('ledger_transaction', models.ForeignKey(help_text="SA transaction équilibrée — pour le Pont de Confiance, la transaction d'encaissement diaspora existante (jamais de double écriture pour le même franc).", on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='trustbridge.ledgertransaction', verbose_name='transaction du ledger')),
                ('payment_intent', models.ForeignKey(blank=True, help_text='Renseigné UNIQUEMENT pour un encaissement Pont de Confiance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='trustbridge.paymentintent', verbose_name='intention de paiement')),
                ('received_by', models.ForeignKey(blank=True, help_text='Agent au guichet ; vide pour un encaissement Pont de Confiance (webhook).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments_received', to=settings.AUTH_USER_MODEL, verbose_name='encaissé par')),
            ],
            options={
                'verbose_name': 'encaissement',
                'verbose_name_plural': 'encaissements',
            },
        ),
        migrations.CreateModel(
            name='CashPaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('reason', models.TextField(help_text='Obligatoire — une contre-passation sans motif est irrecevable.', verbose_name='motif')),
                ('cash_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='trustbridge.cashpayment', verbose_name='encaissement')),
                ('ledger_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payment_reversals', to='trustbridge.ledgertransaction', verbose_name='transaction de contre-passation')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payment_reversals_made', to=settings.AUTH_USER_MODEL, verbose_name='contre-passée par')),
            ],
            options={
                'verbose_name': "contre-passation d'encaissement",
                'verbose_name_plural': "contre-passations d'encaissement",
            },
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='numéro séquentiel')),
                ('amount_kmf', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant (KMF)')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='émis le')),
                ('cash_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipt', to='trustbridge.cashpayment', verbose_name='encaissement')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='centers.healthcenter', verbose_name='centre')),
                ('ledger_transaction', models.ForeignKey(help_text="M3 — la transaction de l'encaissement : le montant du reçu est réconcilié avec le ledger, jamais seulement affirmé.", on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='trustbridge.ledgertransaction', verbose_name='transaction du ledger')),
            ],
            options={
                'verbose_name': 'reçu guichet',
                'verbose_name_plural': 'reçus guichet',
            },
        ),
        migrations.AddConstraint(
            model_name='cashpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf__gt', 0)), name='cash_payment_amount_kmf_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'mobile_money'), ('operator__gt', '')), models.Q(models.Q(('method', 'mobile_money'), _negated=True), ('operator', '')), _connector='OR'), name='cash_payment_operator_iff_mobile_money'),
        ),
        migrations.AddConstraint(
            model_name='cashpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'pont_confiance'), ('payment_intent__isnull', False)), models.Q(models.Q(('method', 'pont_confiance'), _negated=True), ('payment_intent__isnull', True)), _connector='OR'), name='cash_payment_intent_iff_trust_bridge'),
        ),
        migrations.AddConstraint(
            model_name='cashreceipt',
            constraint=models.UniqueConstraint(fields=('center', 'sequence_number'), name='unique_cash_receipt_sequence_per_center'),
        ),
        migrations.AddConstraint(
            model_name='cashreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kmf__gt', 0)), name='cash_receipt_amount_kmf_positive'),
        ),
    ]
