# Generated by Django 5.2.17 on 2026-08-13 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_tariffitem_tariff_price_kmf_integral'),
        ('trustbridge', '0007_cash_append_only_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, help_text='Fournie par le client du guichet pour rendre le POST rejouable sans double encaissement ; unique par centre.', max_length=64, null=True, verbose_name="clé d'idempotence guichet"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text="Obligatoire à l'annulation (service cancel_invoice) — une annulation sans motif est irrecevable.", verbose_name="motif d'annulation"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annulée le'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='annulée par'),
        ),
        migrations.AddConstraint(
            model_name='cashpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('center', 'idempotency_key'), name='unique_cash_idempotency_key_per_center'),
        ),
    ]
