# Generated by Django 5.2.17 on 2026-08-16 01:13

import apps.common.private_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        ('medical', '0004_prescription_delivered_at_prescription_delivered_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('island', models.CharField(choices=[('ngazidja', 'Ngazidja (Grande Comore)'), ('ndzuwani', 'Ndzuwani (Anjouan)'), ('mwali', 'Mwali (Mohéli)')], max_length=16, verbose_name='île')),
                ('city', models.CharField(blank=True, help_text="Vide = toute l'île (la diffusion reste bornée par le plafond).", max_length=128, verbose_name='commune')),
                ('status', models.CharField(choices=[('ouverte', 'Ouverte'), ('close', 'Close')], default='ouverte', max_length=16, verbose_name='statut')),
                ('expires_at', models.DateTimeField(verbose_name='périme le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fermée le')),
                ('close_reason', models.CharField(blank=True, choices=[('manuelle', 'Fermée par le centre'), ('peremption', 'Périmée')], max_length=16, verbose_name='raison de fermeture')),
                ('center', models.ForeignKey(help_text='JAMAIS sérialisé vers une pharmacie (ADR 0022 décision 2).', on_delete=django.db.models.deletion.PROTECT, related_name='availability_requests', to='centers.healthcenter', verbose_name='centre demandeur')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='lancée par')),
                ('prescription', models.ForeignKey(help_text='JAMAIS sérialisée vers une pharmacie — ni elle, ni le patient.', on_delete=django.db.models.deletion.PROTECT, related_name='availability_requests', to='medical.prescription', verbose_name='ordonnance')),
            ],
            options={
                'verbose_name': 'demande de disponibilité',
                'verbose_name_plural': 'demandes de disponibilité',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('medication', models.CharField(max_length=255, verbose_name='médicament')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pharmacy.availabilityrequest', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'médicament demandé',
                'verbose_name_plural': 'médicaments demandés',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRequestRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='pharmacy.availabilityrequest', verbose_name='demande')),
            ],
            options={
                'verbose_name': "destinataire d'une demande",
                'verbose_name_plural': 'destinataires des demandes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('comment', models.CharField(blank=True, max_length=280, verbose_name='commentaire')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='pharmacy.availabilityrequestrecipient', verbose_name='destinataire')),
                ('responded_by', models.ForeignKey(help_text="Interne à l'officine : jamais rendu au centre ni au patient (c'est la pharmacie qui répond, pas une personne).", on_delete=django.db.models.deletion.PROTECT, related_name='availability_responses', to=settings.AUTH_USER_MODEL, verbose_name='répondu par')),
            ],
            options={
                'verbose_name': 'réponse de disponibilité',
                'verbose_name_plural': 'réponses de disponibilité',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityResponseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('is_available', models.BooleanField(verbose_name='disponible')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_lines', to='pharmacy.availabilityrequestitem', verbose_name='médicament demandé')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='pharmacy.availabilityresponse', verbose_name='réponse')),
            ],
            options={
                'verbose_name': 'ligne de réponse',
                'verbose_name_plural': 'lignes de réponse',
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('island', models.CharField(choices=[('ngazidja', 'Ngazidja (Grande Comore)'), ('ndzuwani', 'Ndzuwani (Anjouan)'), ('mwali', 'Mwali (Mohéli)')], max_length=16, verbose_name='île')),
                ('city', models.CharField(max_length=128, verbose_name='ville / commune')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, help_text="Normalisé E.164 par le service (région KM). C'est le numéro que le centre et le patient voient : il est PUBLIC dans le réseau.", max_length=32, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('suspendue', 'Suspendue')], default='en_attente', max_length=16, verbose_name='statut')),
                ('status_reason', models.TextField(blank=True, help_text='Obligatoire pour une suspension. Lu par la pharmacie concernée et par la plateforme — jamais journalisé.', verbose_name='motif de la décision')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='statut décidé le')),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_status_decisions', to=settings.AUTH_USER_MODEL, verbose_name='statut décidé par')),
            ],
            options={
                'verbose_name': 'pharmacie',
                'verbose_name_plural': 'pharmacies',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='availabilityrequestrecipient',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_requests', to='pharmacy.pharmacy', verbose_name='pharmacie'),
        ),
        migrations.CreateModel(
            name='PharmacyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('doc_type', models.CharField(choices=[('registre_commerce', 'Registre du commerce'), ('licence_officine', "Licence d'officine"), ('piece_identite_responsable', "Pièce d'identité du responsable"), ('autre', 'Autre')], max_length=32, verbose_name='type de pièce')),
                ('file', models.FileField(max_length=255, storage=apps.common.private_storage.PrivateMediaStorage(), upload_to='pharmacy_documents/%Y/%m/', verbose_name='fichier')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_documents_archived', to=settings.AUTH_USER_MODEL, verbose_name='archivé par')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pharmacy.pharmacy', verbose_name='pharmacie')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
            ],
            options={
                'verbose_name': "pièce d'une pharmacie",
                'verbose_name_plural': 'pièces des pharmacies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='pharmacy.pharmacy', verbose_name='pharmacie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "membre d'une pharmacie",
                'verbose_name_plural': 'membres des pharmacies',
                'ordering': ['pharmacy_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='availabilityrequest',
            index=models.Index(fields=['center', '-created_at'], name='pharmacy_av_center__a8a396_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityrequest',
            index=models.Index(fields=['prescription'], name='pharmacy_av_prescri_e966b7_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityrequest',
            index=models.Index(fields=['status', 'expires_at'], name='pharmacy_av_status_20f694_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ouverte', 'close'])), name='availability_request_status_is_closed'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrequest',
            constraint=models.CheckConstraint(condition=models.Q(('island__in', ['ngazidja', 'ndzuwani', 'mwali'])), name='availability_request_island_is_closed'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('medication', ''), _negated=True), name='availability_item_medication_not_empty'),
        ),
        migrations.AddIndex(
            model_name='availabilityresponse',
            index=models.Index(fields=['recipient', '-created_at'], name='pharmacy_av_recipie_63cfc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityresponseline',
            constraint=models.UniqueConstraint(fields=('response', 'item'), name='unique_availability_response_line'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['status', 'island', 'city'], name='pharmacy_ph_status_c21db0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['en_attente', 'validee', 'suspendue'])), name='pharmacy_status_is_closed'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.CheckConstraint(condition=models.Q(('island__in', ['ngazidja', 'ndzuwani', 'mwali'])), name='pharmacy_island_is_closed'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pharmacy_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.CheckConstraint(condition=models.Q(('city', ''), _negated=True), name='pharmacy_city_not_empty'),
        ),
        migrations.AddIndex(
            model_name='availabilityrequestrecipient',
            index=models.Index(fields=['pharmacy', '-created_at'], name='pharmacy_av_pharmac_62d262_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrequestrecipient',
            constraint=models.UniqueConstraint(fields=('request', 'pharmacy'), name='unique_availability_recipient'),
        ),
        migrations.AddIndex(
            model_name='pharmacymembership',
            index=models.Index(fields=['user', 'is_active'], name='pharmacy_ph_user_id_dff010_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacymembership',
            constraint=models.UniqueConstraint(fields=('user', 'pharmacy'), name='unique_pharmacy_membership'),
        ),
    ]
