# Generated by Django 5.2.17 on 2026-08-15 00:16

import apps.common.private_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('subject', models.CharField(max_length=200, verbose_name='objet')),
                ('category', models.CharField(choices=[('bug', 'Anomalie'), ('question', 'Question'), ('facturation', 'Facturation'), ('autre', 'Autre')], max_length=16, verbose_name='catégorie')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=16, verbose_name='statut')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', help_text="Déclarée à l'ouverture par la personne qui rencontre le problème — non modifiable ensuite (le tri se fait au statut).", max_length=16, verbose_name='priorité')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fermé le')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='centers.healthcenter', verbose_name='centre')),
                ('opened_by', models.ForeignKey(help_text="N'importe quel membre ACTIF du personnel du centre.", on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets_opened', to=settings.AUTH_USER_MODEL, verbose_name='ouvert par')),
            ],
            options={
                'verbose_name': 'ticket de support',
                'verbose_name_plural': 'tickets de support',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('author_side', models.CharField(choices=[('centre', 'Le centre'), ('chioni', 'Chioni')], help_text='Posé par le service selon la porte empruntée.', max_length=8, verbose_name='côté')),
                ('body', models.TextField(verbose_name='message')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='support.supportticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'message de support',
                'verbose_name_plural': 'messages de support',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('file', models.FileField(max_length=255, storage=apps.common.private_storage.PrivateMediaStorage(), upload_to='support_attachments/%Y/%m/', verbose_name='fichier')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='support.supportticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': "pièce jointe d'un ticket",
                'verbose_name_plural': 'pièces jointes des tickets',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['center', '-created_at'], name='support_sup_center__414790_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='support_sup_status_52a4ed_idx'),
        ),
    ]
