# Generated by Django 5.2.17 on 2026-08-15 18:39

import apps.common.private_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hrm_departments', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'service (RH)',
                'verbose_name_plural': 'services (RH)',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('hired_at', models.DateField(verbose_name='embauché le')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='parti le')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='centers.healthcenter', verbose_name='centre')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='hrm.department', verbose_name='service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to=settings.AUTH_USER_MODEL, verbose_name='personne')),
            ],
            options={
                'verbose_name': 'dossier RH',
                'verbose_name_plural': 'dossiers RH',
                'ordering': ['-hired_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('conge', 'En congé'), ('repos', 'Repos'), ('ferie', 'Férié')], max_length=8, verbose_name='statut')),
                ('noted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records_noted', to=settings.AUTH_USER_MODEL, verbose_name='noté par')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='hrm.employment', verbose_name='dossier RH')),
            ],
            options={
                'verbose_name': 'journée de présence',
                'verbose_name_plural': 'feuille de présence',
                'ordering': ['-date', 'employment_id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('date', models.DateField(verbose_name='date')),
                ('name', models.CharField(max_length=64, verbose_name='libellé')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'jour férié',
                'verbose_name_plural': 'jours fériés',
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hrm_job_titles', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'fonction',
                'verbose_name_plural': 'fonctions',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='job_title',
            field=models.ForeignKey(blank=True, help_text="Libellé d'organisation. N'ouvre AUCUN droit : les permissions viennent du rôle du membership (ADR 0020, décision 2).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='hrm.jobtitle', verbose_name='fonction'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('leave_type', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('deuil', 'Congé de deuil'), ('sans_solde', 'Congé sans solde'), ('autre', 'Autre')], help_text="Choix FERMÉS. Il n'existe volontairement aucun champ de motif libre : un motif de congé est de la donnée de santé ou de vie privée (ADR 0020, décision 4).", max_length=16, verbose_name='type de congé')),
                ('start_date', models.DateField(verbose_name='du')),
                ('end_date', models.DateField(verbose_name='au')),
                ('status', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='demande', max_length=10, verbose_name='statut')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='décidé le')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='décidé par')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hrm.employment', verbose_name='dossier RH')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
            ],
            options={
                'verbose_name': 'demande de congé',
                'verbose_name_plural': 'demandes de congé',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('file', models.FileField(max_length=255, storage=apps.common.private_storage.PrivateMediaStorage(), upload_to='leave_documents/%Y/%m/', verbose_name='fichier')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_documents_archived', to=settings.AUTH_USER_MODEL, verbose_name='archivé par')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hrm.leaverequest', verbose_name='demande de congé')),
            ],
            options={
                'verbose_name': 'justificatif de congé',
                'verbose_name_plural': 'justificatifs de congé',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('center', 'name'), name='unique_hrm_department_per_center'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='hrm_attenda_date_fb512c_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employment', 'date'), name='unique_attendance_per_employment_day'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('center', 'date'), name='unique_holiday_per_center_date'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('center', 'name'), name='unique_hrm_job_title_per_center'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['center', 'ended_at'], name='hrm_employm_center__84cb88_idx'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(fields=('user', 'center'), name='unique_employment_per_user_center'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('hired_at')), _connector='OR'), name='employment_end_after_hire'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employment', 'status'], name='hrm_leavere_employm_0e7e7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status', 'demande')), models.Q(models.Q(('status', 'demande'), _negated=True), ('decided_at__isnull', False)), _connector='OR'), name='leave_decision_matches_status'),
        ),
    ]
