# Generated by Django 5.2.17 on 2026-08-15 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        ('medical', '0003_enriched_patient_record'),
        ('patients', '0004_extended_identity_and_insurance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'chambre',
                'verbose_name_plural': 'chambres',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='inpatient.room', verbose_name='chambre')),
            ],
            options={
                'verbose_name': 'lit',
                'verbose_name_plural': 'lits',
                'ordering': ['room__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('admitted_at', models.DateTimeField(verbose_name='admis le')),
                ('discharged_at', models.DateTimeField(blank=True, null=True, verbose_name='sorti le')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('sortie', 'Sorti'), ('annule', 'Annulé')], default='en_cours', max_length=16, verbose_name='statut')),
                ('priority', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], default='normale', max_length=16, verbose_name='priorité')),
                ('cancel_reason', models.TextField(blank=True, help_text="Obligatoire pour annuler une admission saisie par erreur. Jamais un motif d'admission (celui-là est clinique) et jamais en payload d'audit.", verbose_name="motif d'annulation")),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays_admitted', to=settings.AUTH_USER_MODEL, verbose_name='admis par')),
                ('attending', models.ManyToManyField(blank=True, help_text="Plusieurs intervenants possibles, réassignables — c'est la raison pour laquelle un séjour n'est pas un Encounter (dont le praticien est un singleton non-nul).", related_name='inpatient_stays_attended', to='centers.staffmembership', verbose_name='médecins assignés')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='centers.healthcenter', verbose_name='centre')),
                ('encounter', models.OneToOneField(help_text="Porte la production clinique et la facturation du séjour (ADR 0019 §1). Ouverte à l'admission, clôturée à la sortie.", on_delete=django.db.models.deletion.PROTECT, related_name='stay', to='medical.encounter', verbose_name='consultation pivot')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='patients.patientprofile', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'séjour',
                'verbose_name_plural': 'séjours',
                'ordering': ['-admitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('assigned_at', models.DateTimeField(verbose_name='occupé depuis')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='libéré le')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigné par')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inpatient.bed', verbose_name='lit')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments_released', to=settings.AUTH_USER_MODEL, verbose_name='libéré par')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments', to='inpatient.stay', verbose_name='séjour')),
            ],
            options={
                'verbose_name': 'occupation de lit',
                'verbose_name_plural': 'occupations de lit',
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('center', 'name'), name='unique_room_name_per_center'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_bed_name_per_room'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['center', 'status'], name='inpatient_s_center__e0c4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['patient', '-admitted_at'], name='inpatient_s_patient_9e9ad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('bed',), name='unique_open_assignment_per_bed'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('stay',), name='unique_open_assignment_per_stay'),
        ),
    ]
