# Generated by Django 5.2.17 on 2026-08-15 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_kyc_file_and_documents'),
        ('inpatient', '0001_initial'),
        ('medical', '0003_enriched_patient_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StayDayBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('days', models.PositiveSmallIntegerField(verbose_name='journées facturées')),
                ('idempotency_key', models.CharField(help_text="Fournie par le client, OBLIGATOIRE : rejouer la même clé renvoie la même facturation au lieu d'en poser une seconde. Unique par centre (contrainte DB).", max_length=64, verbose_name="clé d'idempotence")),
                ('acts', models.ManyToManyField(help_text='Les N actes que CE geste a posés sur la consultation pivot.', related_name='stay_day_billings', to='medical.actperformed', verbose_name='actes posés')),
                ('billed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_day_billings', to=settings.AUTH_USER_MODEL, verbose_name='facturé par')),
                ('center', models.ForeignKey(help_text="Dénormalisation de ``stay.center`` : c'est elle qui porte l'unicité de la clé d'idempotence (patron CashPayment).", on_delete=django.db.models.deletion.PROTECT, related_name='stay_day_billings', to='centers.healthcenter', verbose_name='centre')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_billings', to='inpatient.stay', verbose_name='séjour')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_day_billings', to='centers.tariffitem', verbose_name='tarif appliqué')),
            ],
            options={
                'verbose_name': 'facturation de journées',
                'verbose_name_plural': 'facturations de journées',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('center', 'idempotency_key'), name='unique_stay_day_billing_key_per_center'), models.CheckConstraint(condition=models.Q(('days__gte', 1)), name='stay_day_billing_days_positive')],
            },
        ),
    ]
