# Generated by Django 5.2.17 on 2026-08-12 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('type', models.CharField(choices=[('hopital_public', 'Hôpital public'), ('clinique_privee', 'Clinique privée'), ('centre_sante', 'Centre de santé'), ('cabinet', 'Cabinet médical'), ('pharmacie', 'Pharmacie')], max_length=32, verbose_name="type d'établissement")),
                ('island', models.CharField(choices=[('ngazidja', 'Ngazidja (Grande Comore)'), ('ndzuwani', 'Ndzuwani (Anjouan)'), ('mwali', 'Mwali (Mohéli)')], max_length=16, verbose_name='île')),
                ('city', models.CharField(max_length=128, verbose_name='ville / localité')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('kyc_status', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='en_attente', help_text="Un centre ne peut recevoir de paiements qu'une fois vérifié (actif).", max_length=16, verbose_name='statut KYC')),
            ],
            options={
                'verbose_name': 'centre de santé',
                'verbose_name_plural': 'centres de santé',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('role', models.CharField(choices=[('directeur', 'Directeur'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier / Infirmière'), ('sage_femme', 'Sage-femme'), ('secretaire', 'Secrétaire'), ('caissier', 'Caissier / Caissière'), ('pharmacien', 'Pharmacien / Pharmacienne')], max_length=16, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to='centers.healthcenter', verbose_name='centre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'membre du personnel',
                'verbose_name_plural': 'membres du personnel',
                'constraints': [models.UniqueConstraint(fields=('user', 'center', 'role'), name='unique_membership_per_user_center_role')],
            },
        ),
        migrations.CreateModel(
            name='TariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('generic_category', models.CharField(choices=[('consultation', 'Consultation'), ('analyses_examens', 'Analyses et examens'), ('medicaments', 'Médicaments'), ('hospitalisation', 'Hospitalisation'), ('acte_technique', 'Acte technique'), ('soins_infirmiers', 'Soins infirmiers'), ('maternite', 'Maternité'), ('autre', 'Autre')], default='autre', help_text='Seule information de soin visible du tuteur (portée « paiements »). Le libellé détaillé relève du détail clinique.', max_length=24, verbose_name='nature générique')),
                ('price_kmf', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix (KMF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items', to='centers.healthcenter', verbose_name='centre')),
            ],
            options={
                'verbose_name': 'tarif',
                'verbose_name_plural': 'grille tarifaire',
                'constraints': [models.UniqueConstraint(fields=('center', 'code'), name='unique_tariff_code_per_center'), models.CheckConstraint(condition=models.Q(('price_kmf__gte', 0)), name='tariff_price_kmf_positive')],
            },
        ),
    ]
