# Generated by Django 5.2.17 on 2026-08-13 16:30

import apps.centers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='logo',
            field=models.ImageField(blank=True, help_text="Affiché en sidebar, sur les factures et reçus à l'écran (l'impression PDF viendra avec le chantier PDF).", upload_to=apps.centers.models.center_logo_upload_to, verbose_name='logo'),
        ),
    ]
