# Generated by Django 5.2.17 on 2026-08-13 18:20

import apps.common.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_healthcenter_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffitem',
            name='price_kmf',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.common.money.validate_kmf_integral], verbose_name='prix (KMF)'),
        ),
    ]
