# Generated by Django 5.2.17 on 2026-08-13 21:43 — then hand-edited (S1):
# a RunPython guard runs BEFORE the constraint and REFUSES the migration
# with a clear French message when fractional tariff rows exist. NEVER a
# silent rounding: a price is money a center chose — only a human corrects
# it (vigilance 2a, ADR 0015 addendum S1).

import django.db.models.functions.math
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Round


def forbid_fractional_tariffs(apps, schema_editor):
    """Fail fast, in French, listing the offending rows — the raw
    IntegrityError of AddConstraint would be unreadable and give no
    remediation path."""
    TariffItem = apps.get_model("centers", "TariffItem")
    fractional = list(
        TariffItem.objects.exclude(price_kmf=Round(F("price_kmf")))
        .values_list("pk", "code", "price_kmf")
    )
    if fractional:
        rows = ", ".join(
            f"#{pk} [{code}] {price} KMF" for pk, code, price in fractional
        )
        raise RuntimeError(
            "Migration refusée : la grille tarifaire contient "
            f"{len(fractional)} tarif(s) à prix fractionnaire ({rows}). "
            "Le franc comorien ne porte pas de décimales : corrigez ces "
            "prix À LA MAIN (jamais d'arrondi automatique — un prix est "
            "une décision du centre), puis relancez la migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_tariffitem_price_kmf'),
    ]

    operations = [
        # Reversible: the guard is read-only (noop backwards), the
        # constraint drops cleanly.
        migrations.RunPython(forbid_fractional_tariffs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tariffitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_kmf', django.db.models.functions.math.Round('price_kmf'))), name='tariff_price_kmf_integral'),
        ),
    ]
