# Generated by Django 5.2.17 on 2026-08-14 17:29

import apps.common.private_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_tariffitem_tariff_price_kmf_integral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='kyc_reason',
            field=models.TextField(blank=True, help_text='Obligatoire pour une suspension. Visible de la plateforme et du directeur du centre — jamais du patient ni du tuteur.', verbose_name='motif de la décision KYC'),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='kyc_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC décidé le'),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='kyc_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_decisions', to=settings.AUTH_USER_MODEL, verbose_name='KYC décidé par'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='kyc_status',
            field=models.CharField(choices=[('en_attente', 'En attente de vérification'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='en_attente', help_text="Un centre ne peut recevoir de paiements de la diaspora qu'une fois vérifié (actif). « suspendu » ferme le RAIL DIASPORA et lui seul : le soin et la caisse locale continuent (ADR 0017).", max_length=16, verbose_name='statut KYC'),
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('doc_type', models.CharField(choices=[('registre_commerce', 'Registre du commerce'), ('licence_sante', 'Licence sanitaire'), ('piece_identite_directeur', "Pièce d'identité du directeur"), ('autre', 'Autre')], max_length=32, verbose_name='type de pièce')),
                ('file', models.FileField(max_length=255, storage=apps.common.private_storage.PrivateMediaStorage(), upload_to='kyc_documents/%Y/%m/', verbose_name='fichier')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_documents_archived', to=settings.AUTH_USER_MODEL, verbose_name='archivé par')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_documents', to='centers.healthcenter', verbose_name='centre')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
            ],
            options={
                'verbose_name': 'pièce KYC',
                'verbose_name_plural': 'pièces KYC',
                'ordering': ['-created_at'],
            },
        ),
    ]
