# Generated by Django 5.2.17 on 2026-08-13 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('patients', '0003_alter_guardianlink_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('scheduled_at', models.DateTimeField(verbose_name='prévu le')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20, verbose_name='durée (minutes)')),
                ('reason', models.CharField(blank=True, help_text='Note de guichet visible de tout le staff du centre — jamais un contenu clinique (voir docstring du modèle).', max_length=255, verbose_name='motif opérationnel')),
                ('status', models.CharField(choices=[('prevu', 'Prévu'), ('arrive', "Arrivé (salle d'attente)"), ('honore', 'Honoré'), ('manque', 'Manqué'), ('annule', 'Annulé')], default='prevu', max_length=16, verbose_name='statut')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text="Anti-doublon du rappel J-1 (tâche beat quotidienne). Remis à NULL quand le rendez-vous est déplacé : un créneau qui change après l'envoi du rappel redevient éligible s'il retombe sur « demain ».", null=True, verbose_name='rappel envoyé le')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='centers.healthcenter', verbose_name='centre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patientprofile', verbose_name='patient')),
                ('practitioner', models.ForeignKey(blank=True, help_text='Optionnel : un rendez-vous peut être pris « avec le centre ».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='centers.staffmembership', verbose_name='praticien')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['center', 'scheduled_at'], name='scheduling__center__19cd28_idx'), models.Index(fields=['practitioner', 'scheduled_at'], name='scheduling__practit_a18b6d_idx')],
            },
        ),
    ]
